In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('train.csv')

In [3]:
dataset.isnull().sum()

PassengerId      0
Cabin          687
Ticket           0
Name             0
Sex              0
Pclass           0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
Survived         0
dtype: int64

In [4]:
dataset.dropna(subset=['Embarked'], inplace=True)

In [5]:
dataset.isnull().sum()

PassengerId      0
Cabin          687
Ticket           0
Name             0
Sex              0
Pclass           0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         0
Survived         0
dtype: int64

In [6]:
X = dataset.iloc[:, 4:-1].values
y = dataset.iloc[:, -1].values

In [7]:
X

array([['male', 3, 22.0, ..., 0, 7.25, 'S'],
       ['female', 1, 38.0, ..., 0, 71.2833, 'C'],
       ['female', 3, 26.0, ..., 0, 7.925, 'S'],
       ...,
       ['female', 3, nan, ..., 2, 23.45, 'S'],
       ['male', 1, 26.0, ..., 0, 30.0, 'C'],
       ['male', 3, 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [8]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:3])
X[:, 2:3] = imputer.transform(X[:, 2:3])

In [10]:
X

array([['male', 3, 22.0, ..., 0, 7.25, 'S'],
       ['female', 1, 38.0, ..., 0, 71.2833, 'C'],
       ['female', 3, 26.0, ..., 0, 7.925, 'S'],
       ...,
       ['female', 3, 29.64209269662921, ..., 2, 23.45, 'S'],
       ['male', 1, 26.0, ..., 0, 30.0, 'C'],
       ['male', 3, 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])

In [12]:
X

array([[1, 3, 22.0, ..., 0, 7.25, 'S'],
       [0, 1, 38.0, ..., 0, 71.2833, 'C'],
       [0, 3, 26.0, ..., 0, 7.925, 'S'],
       ...,
       [0, 3, 29.64209269662921, ..., 2, 23.45, 'S'],
       [1, 1, 26.0, ..., 0, 30.0, 'C'],
       [1, 3, 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
X

array([[0.0, 0.0, 1.0, ..., 1, 0, 7.25],
       [1.0, 0.0, 0.0, ..., 1, 0, 71.2833],
       [0.0, 0.0, 1.0, ..., 0, 0, 7.925],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 2, 23.45],
       [1.0, 0.0, 0.0, ..., 0, 0, 30.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 7.75]], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [16]:
X_train

array([[0.0, 1.0, 0.0, ..., 1, 0, 15.5],
       [1.0, 0.0, 0.0, ..., 0, 0, 79.2],
       [0.0, 0.0, 1.0, ..., 1, 0, 7.0458],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 0, 30.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 7.75],
       [1.0, 0.0, 0.0, ..., 1, 2, 41.5792]], dtype=object)

In [17]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier()

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1])

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[88 17]
 [30 43]]


0.7359550561797753

In [21]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 84.24 %
Standard Deviation: 5.35 %


In [22]:
testdata = pd.read_csv('test.csv')

In [23]:
testdata

PassengerId              Ticket Cabin  \
0            892              330911   NaN   
1            893              363272   NaN   
2            894              240276   NaN   
3            895              315154   NaN   
4            896             3101298   NaN   
..           ...                 ...   ...   
413         1305           A.5. 3236   NaN   
414         1306            PC 17758  C105   
415         1307  SOTON/O.Q. 3101262   NaN   
416         1308              359309   NaN   
417         1309                2668   NaN   

                                             Name     Sex  Pclass   Age  \
0                                Kelly, Mr. James    male       3  34.5   
1                Wilkes, Mrs. James (Ellen Needs)  female       3  47.0   
2                       Myles, Mr. Thomas Francis    male       2  62.0   
3                                Wirz, Mr. Albert    male       3  27.0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female       3  22.0   
..                                            ...     ...     ...   ...   
413                            Spector, Mr. Woolf    male       3   NaN   
414                  Oliva y Ocana, Dona. Fermina  female       1  39.0   
415                  Saether, Mr. Simon Sivertsen    male       3  38.5   
416                           Ware, Mr. Frederick    male       3   NaN   
417                      Peter, Master. Michael J    male       3   NaN   

     SibSp  Parch      Fare Embarked  
0        0      0    7.8292        Q  
1        1      0    7.0000        S  
2        0      0    9.6875        Q  
3        0      0    8.6625        S  
4        1      1   12.2875        S  
..     ...    ...       ...      ...  
413      0      0    8.0500        S  
414      0      0  108.9000        C  
415      0      0    7.2500        S  
416      0      0    8.0500        S  
417      1      1   22.3583        C  

[418 rows x 11 columns]

In [24]:
testdata.isnull().sum()

PassengerId      0
Ticket           0
Cabin          327
Name             0
Sex              0
Pclass           0
Age             86
SibSp            0
Parch            0
Fare             1
Embarked         0
dtype: int64

In [25]:
X_test = testdata.iloc[:, 4:].values

In [26]:
X_test

array([['male', 3, 34.5, ..., 0, 7.8292, 'Q'],
       ['female', 3, 47.0, ..., 0, 7.0, 'S'],
       ['male', 2, 62.0, ..., 0, 9.6875, 'Q'],
       ...,
       ['male', 3, 38.5, ..., 0, 7.25, 'S'],
       ['male', 3, nan, ..., 0, 8.05, 'S'],
       ['male', 3, nan, ..., 1, 22.3583, 'C']], dtype=object)

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_test[:, 5:6])
X_test[:, 5:6] = imputer.transform(X_test[:, 5:6])

In [28]:
X_test

array([['male', 3, 34.5, ..., 0, 7.8292, 'Q'],
       ['female', 3, 47.0, ..., 0, 7.0, 'S'],
       ['male', 2, 62.0, ..., 0, 9.6875, 'Q'],
       ...,
       ['male', 3, 38.5, ..., 0, 7.25, 'S'],
       ['male', 3, nan, ..., 0, 8.05, 'S'],
       ['male', 3, nan, ..., 1, 22.3583, 'C']], dtype=object)

In [29]:
testdata.isnull().sum()

PassengerId      0
Ticket           0
Cabin          327
Name             0
Sex              0
Pclass           0
Age             86
SibSp            0
Parch            0
Fare             1
Embarked         0
dtype: int64

In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_test[:, 2:3])
X_test[:, 2:3] = imputer.transform(X_test[:, 2:3])

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_test[:, 0] = le.fit_transform(X_test[:, 0])

In [32]:
X_test

array([[1, 3, 34.5, ..., 0, 7.8292, 'Q'],
       [0, 3, 47.0, ..., 0, 7.0, 'S'],
       [1, 2, 62.0, ..., 0, 9.6875, 'Q'],
       ...,
       [1, 3, 38.5, ..., 0, 7.25, 'S'],
       [1, 3, 30.272590361445783, ..., 0, 8.05, 'S'],
       [1, 3, 30.272590361445783, ..., 1, 22.3583, 'C']], dtype=object)

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X_test = np.array(ct.fit_transform(X_test))

In [34]:
X_test

array([[0.0, 1.0, 0.0, ..., 0, 0, 7.8292],
       [0.0, 0.0, 1.0, ..., 1, 0, 7.0],
       [0.0, 1.0, 0.0, ..., 0, 0, 9.6875],
       ...,
       [0.0, 0.0, 1.0, ..., 0, 0, 7.25],
       [0.0, 0.0, 1.0, ..., 0, 0, 8.05],
       [1.0, 0.0, 0.0, ..., 1, 1, 22.3583]], dtype=object)

In [35]:
testdata.isnull().sum()

PassengerId      0
Ticket           0
Cabin          327
Name             0
Sex              0
Pclass           0
Age             86
SibSp            0
Parch            0
Fare             1
Embarked         0
dtype: int64

In [36]:
y_test_pred = classifier.predict(X_test)

In [37]:
y_test_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [38]:
df_pred = pd.DataFrame({'Survived': y_test_pred})

In [39]:
df_pred

Survived
0           0
1           0
2           0
3           0
4           0
..        ...
413         0
414         1
415         0
416         0
417         0

[418 rows x 1 columns]

In [40]:
id= testdata.iloc[:, 0].values
df_id = pd.DataFrame({'PassengerId': id})

In [41]:
df_id

PassengerId
0            892
1            893
2            894
3            895
4            896
..           ...
413         1305
414         1306
415         1307
416         1308
417         1309

[418 rows x 1 columns]

In [42]:
df = pd.concat([df_id, df_pred], axis=1)

In [43]:
df

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [44]:
df.to_csv('titanic_test_pred.csv')

In [45]:
df.to_csv('titanic_test_pred1.csv', index=False)